administer domain config ui:
  title: 'Administer Domain Config UI settings'
  description: 'Allows administrators to determine what forms are available for domain-specific configuration.'
  restrict access: true
set default domain configuration:
  title: 'Set the default configuration for all sites'
  description: 'Allows domain administrators to set the default value for a configuration. The default value is used for all sites without a domain-specific configuration.'
  restrict access: true
translate domain configuration:
  title: 'Translate domain-specific configurations'
  description: 'Allows domain administrators to use language-specific configuration forms specific to their managed domains.'
  restrict access: true
use domain config ui:
  title: 'Manage domain-specific configurations'
  description: 'Allows domain administrators to use configuration forms specific to their managed domains.'
  restrict access: true
